export const timeline = [
  { year: 1666, milestone: false, text: 'Marcello Malpighi first describes the microanatomy of the renal glomerulus using the newly developed microscope, founding the science of renal histology.' },
  { year: 1827, milestone: false, text: 'Richard Bright describes clinical renal syndromes and correlates them with kidney pathology, laying the foundation for what would become nephrology.' },
  { year: 1914, milestone: false, text: 'Franz Volhard and Theodor Fahr publish the first systematic histopathology classification of renal disease, establishing pathology as central to understanding kidney disorders.' },
  { year: 1951, milestone: true, text: 'Iversen and Brun perform the first published percutaneous kidney biopsies, launching the modern era of renal pathology.' },
  { year: 1955, milestone: false, text: 'Immunofluorescence microscopy first applied to renal tissue by Mellors, allowing identification of immune deposits in glomerular disease for the first time. Robert McCluskey and Gloria Gallo at NYU were pioneers in its application to human kidney biopsies.' },
  { year: 1957, milestone: false, text: 'Electron microscopy reveals the fine structure of the glomerulus for the first time, including podocyte foot processes, the glomerular basement membrane, and the mesangium.' },
  { year: 1961, milestone: false, text: 'The CIBA Symposium in London brings together clinicians and pathologists to assess the future of kidney biopsy, establishing it as standard of care at major renal centres worldwide.' },
  { year: 1966, milestone: false, text: 'Robert Heptinstall publishes the first edition of Pathology of the Kidney, the field\'s foundational textbook.' },
  { year: 1977, milestone: true, text: 'Conrad Pirani convenes founding members at the ASN meeting in Washington, D.C. The Renal Pathology Club is born.' },
  { year: 1978, milestone: true, text: 'First Renal Pathology Club scientific symposium held in New Orleans — Topic: Focal segmental glomerulosclerosis. Constitution and bylaws established.' },
  { year: 1981, milestone: false, text: 'The Renal Pathology Club accepts ASN co-sponsorship of a jointly sponsored scientific session. Robert Heptinstall becomes second President.' },
  { year: 1991, milestone: false, text: 'The Renal Pathology Club becomes the 13th official USCAP Companion Society.' },
  { year: 1991, milestone: false, text: 'The first Banff Conference on Allograft Pathology is held in Banff, Alberta, led by Kim Solez and Lorraine Racusen, establishing the first international consensus classification for renal allograft pathology.' },
  { year: 1993, milestone: true, text: 'The Renal Pathology Club formally evolves into the Renal Pathology Society. Gloria Gallo becomes first RPS President.' },
  { year: 1995, milestone: false, text: 'Young Investigator Award established; Shane Meehan is the first recipient.' },
  { year: 1997, milestone: false, text: 'Jacob Churg Award established; J. Charles Jennette is the first recipient.' },
  { year: 1998, milestone: false, text: 'An annual Renal Pathology precourse at ASN began under the direction of Agnes Fogo, reflecting the growing integration of renal pathology into nephrology education.' },
  { year: 2004, milestone: false, text: 'ISN/RPS classification of lupus glomerulonephritis published — a landmark multi-institutional consensus.' },
  { year: 2006, milestone: false, text: 'Young Investigator Award renamed the Liliane Striker Young Investigator Award. Conrad Pirani Travel Award established.' },
  { year: 2007, milestone: false, text: '30th anniversary celebration at USCAP in San Diego honours founding members.' },
  { year: 2009, milestone: false, text: 'Oxford classification of IgA nephropathy released. Gloria Gallo Research Award established.' },
  { year: 2025, milestone: false, text: 'RPS surpasses 400 regular members across 30+ countries, with additional trainee membership growing the community further.' },
  { year: 2027, milestone: true, text: 'RPS\'s 50th birthday — celebrating 5 decades since Conrad Pirani gathered the founding members in Washington, D.C. to form our society.' },
]

export const publications = [
  {
    year: '1991 · Published 1993',
    title: 'International standardization of criteria for the histologic diagnosis of renal allograft rejection: the Banff working classification of kidney transplant pathology',
    journal: 'Kidney International, 1993;44:411–422',
    description: 'Led by Kim Solez and Lorraine Racusen, the inaugural Banff meeting established the first internationally agreed-upon classification for renal allograft pathology. Biennial updates have continued ever since.',
  },
  {
    year: '2004',
    title: 'ISN/RPS classification of lupus nephritis',
    journal: 'Journal of the American Society of Nephrology',
    description: 'A joint ISN/RPS effort replacing prior classifications with a revised, clinically meaningful system for lupus nephritis, now used universally in pathology reporting and clinical trials.',
  },
  {
    year: '2009',
    title: 'Oxford classification of IgA nephropathy',
    journal: 'Kidney International',
    description: 'The MEST scoring system provided the first evidence-based, reproducible pathological classification for IgA nephropathy, developed through an international RPS-affiliated collaboration.',
  },
]

export const events = [
  {
    name: 'Banff Conference on Allograft Pathology',
    dates: 'October 5–9, 2026',
    location: 'Banff, Alberta',
    description: null,
    link: 'https://site.pheedloop.com/event/2026banffmeeting/home',
  },
  {
    name: 'ASN Kidney Week 2026',
    dates: 'October 22–25, 2026',
    location: 'Denver, CO',
    description: null,
    link: 'https://www.asn-online.org/education/kidneyweek/',
  },
  {
    name: '🎂 RPS 50th Birthday Party 🎂',
    dates: 'March 14, 2027 (USCAP 2026 meeting)',
    location: 'Vancouver, BC',
    description: 'Celebrating five decades of the Renal Pathology Society at USCAP 2027. Details to be announced.',
    link: null,
  },
]

export const awards = {
  heptinstall: {
    name: 'Robert H. Heptinstall Lifetime Achievement Award',
    description: 'Dr. Robert H. Heptinstall was the retired Blaxley Professor of Pathology and Pathologist-in-Chief of Johns Hopkins University and Johns Hopkins Hospital. The award recognised individuals who achieved a stellar career in pathology with pioneering discoveries and outstanding contributions to renal pathology. RPS members travelled to his home in Baltimore on November 8, 2011 to present Dr. Heptinstall with the award bearing his name.',
    recipients: [
      { year: 2026, name: 'Agnes Fogo' },
      { year: 2025, name: 'Vivette D\'Agati' },
      { year: 2024, name: 'Parmjeet Randhawa' },
      { year: 2023, name: 'Mark Haas' },
      { year: 2022, name: 'Herbert Terence Cook' },
      { year: 2021, name: 'Lorraine Racusen' },
      { year: 2020, name: 'Charles Jennette' },
      { year: 2019, name: 'Michael Kashgarian' },
      { year: 2014, name: 'Hidekazu Shigematsu' },
      { year: 2011, name: 'Robert B. Colvin' },
      { year: 2011, name: 'Robert H. Heptinstall' },
      { year: 2010, name: 'Michael J. Mihatsch' },
      { year: 2006, name: 'Robert Timmons McCluskey' },
      { year: 2006, name: 'Gloria Gallo' },
    ],
  },
  churg: {
    name: 'Jacob Churg Award',
    description: 'Presented annually at the USCAP RPS event to an individual who has made major contributions to the field of nephropathology. Established by Barnert Hospital, where Dr. Churg spent a substantial portion of his career prior to his retirement in 1996.',
    recipients: [
      { year: 2026, name: 'Lynn Cornell' },
      { year: 2025, name: 'Glen Markowitz' },
      { year: 2024, name: 'Laura Barisoni' },
      { year: 2023, name: 'Patrick D. Walker' },
      { year: 2022, name: 'Samih Nasr' },
      { year: 2021, name: 'Ingeborg Bajema' },
      { year: 2020, name: 'Sanjeev Sethi' },
      { year: 2019, name: 'Michael Mengel' },
      { year: 2018, name: 'Volker Nickoleit' },
      { year: 2017, name: 'Stephen Bonsib' },
      { year: 2016, name: 'Parmjeet Randhawa' },
      { year: 2015, name: 'Ian S. Roberts' },
      { year: 2014, name: 'Surya V. Seshan' },
      { year: 2013, name: 'H. Terence Cook' },
      { year: 2012, name: 'Mark Haas' },
      { year: 2011, name: 'Helen Liapis' },
      { year: 2010, name: 'Cynthia Nast' },
      { year: 2009, name: 'Lorraine Racusen' },
      { year: 2008, name: 'Gary S. Hill' },
      { year: 2007, name: 'Seymour Rosen' },
      { year: 2006, name: 'Helmut Rennke' },
      { year: 2005, name: 'Arthur Cohen' },
      { year: 2004, name: 'Michael Kashgarian' },
      { year: 2003, name: 'Charlie Alpers' },
      { year: 2002, name: 'Fred Silva' },
      { year: 2001, name: 'Melvin Schwartz' },
      { year: 2000, name: 'Vivette D\'Agati' },
      { year: 1999, name: 'Agnes Fogo' },
      { year: 1998, name: 'Robert B. Colvin' },
      { year: 1997, name: 'J. Charles Jennette' },
    ],
  },
  gallo: {
    name: 'Gloria Gallo Research Award',
    description: 'Established in 2009 to honour Gloria Gallo\'s research contributions and her role in the RPS. Awarded to a mid-career investigator who made significant research contributions to renal pathology.',
    recipients: [
      { year: 2025, name: 'Satoru Kudose' },
      { year: 2024, name: 'Tiffany Caza' },
      { year: 2023, name: 'Nicole K. Andeen' },
      { year: 2022, name: 'Benjamin Adam' },
      { year: 2021, name: 'Avi Z. Rosenberg' },
      { year: 2020, name: 'Shreeram Akilesh' },
      { year: 2019, name: 'Ibrahim Batal' },
      { year: 2019, name: 'Astrid Weins' },
      { year: 2017, name: 'Peter Boor' },
      { year: 2016, name: 'Chris Larsen' },
      { year: 2015, name: 'Lynn Cornell' },
      { year: 2015, name: 'Jeffrey Hodgin' },
      { year: 2013, name: 'Samih Nasr' },
      { year: 2012, name: 'Banu Sis' },
      { year: 2011, name: 'Glen Markowitz' },
      { year: 2010, name: 'Laura Barisoni-Thomas' },
      { year: 2009, name: 'Michael Mengel' },
    ],
  },
  striker: {
    name: 'Liliane Striker Young Investigator Award',
    description: 'Named in 2006 after Liliane Striker in recognition of her contributions to renal research. Awarded to fellows and junior faculty for excellence in renal pathology research.',
    recipients: [
      { year: 2023, name: 'Bangchen Wang' },
      { year: 2022, name: 'Ira Doressa Anne L. How' },
      { year: 2022, name: 'Odia Molen' },
      { year: 2022, name: 'Fan Fan' },
      { year: 2020, name: 'Tiffany Caza' },
      { year: 2017, name: 'Alexander Gallan' },
      { year: 2014, name: 'Peter Boor' },
      { year: 2012, name: 'Carla Ellis' },
      { year: 2012, name: 'Samar M. Said' },
      { year: 2011, name: 'Jamie S. Chua' },
      { year: 2010, name: 'Miguel Fernando Palma Diaz' },
      { year: 2009, name: 'Mariam van Groningen' },
      { year: 2008, name: 'Yiqin Zuo' },
      { year: 2007, name: 'Joris J. Roelofs' },
      { year: 2006, name: 'John Keeling' },
      { year: 2005, name: 'Xiubin Liang' },
      { year: 2004, name: 'Hai-Chun Yang' },
      { year: '2002–2003', name: 'Adrian A. Suarez' },
      { year: 2001, name: 'Michael Eikmans' },
      { year: 2000, name: 'Li-jun Ma' },
      { year: 1999, name: 'Peter Heeringa' },
      { year: 1998, name: 'Glen Markowitz' },
      { year: 1997, name: 'Hitendra S. Jethwa' },
      { year: 1997, name: 'Jorge Isaac' },
      { year: 1996, name: 'Tsuyoshi Oikawa' },
      { year: 1996, name: 'Hugh B. Carey' },
      { year: 1995, name: 'Shane Meehan' },
    ],
  },
}

export const foundingMembers = [
  'Conrad Pirani', 'Jacob Churg', 'Robert Heptinstall', 'Michael Kashgarian',
  'Ramzi Cotran', 'Robert McCluskey', 'David Jones', 'Gary Striker',
  'Benjamin Spargo', 'Peter Burkholder', 'Francis Cuppage', 'Richard Kempson',
  'John Kissane', 'Kash Mostofi',
]

export const presidents = [
  { year: 1993, name: 'Gloria Gallo' },
  { year: 1994, name: 'Michael Kashgarian' },
  { year: 1995, name: 'Fred Silva' },
  { year: 1996, name: 'Vivette D\'Agati' },
  { year: 1997, name: 'Arthur Cohen' },
  { year: 1998, name: 'Robert Colvin' },
  { year: 1999, name: 'Seymour Rosen' },
  { year: 2000, name: 'Charles Alpers' },
  { year: 2001, name: 'Melvin Schwartz' },
  { year: 2002, name: 'Agnes Fogo' },
  { year: 2003, name: 'Cynthia Nast' },
  { year: 2004, name: 'Charles Jennette' },
  { year: 2005, name: 'Lorraine Racusen' },
  { year: 2006, name: 'Jan Bruijn' },
  { year: 2007, name: 'Stephen Bonsib' },
  { year: 2008, name: 'Mark Haas' },
  { year: 2009, name: 'Surya Seshan' },
  { year: 2010, name: 'Maria Picken' },
  { year: 2011, name: 'Terry Cook' },
  { year: 2012, name: 'Guillermo Herrera' },
  { year: 2013, name: 'Volker Nickeleit' },
  { year: 2014, name: 'Helen Liapis' },
  { year: 2015, name: 'Glen Markowitz' },
  { year: 2016, name: 'Ian Roberts' },
  { year: 2017, name: 'Anthony Chang' },
  { year: 2018, name: 'James Pullman' },
  { year: 2019, name: 'Laura Barisoni' },
  { year: 2020, name: 'Michael Mengel' },
  { year: 2021, name: 'Parmjeet Randhawa' },
  { year: 2022, name: 'Ingeborg Bajema' },
  { year: 2023, name: 'Lois Arend' },
  { year: 2024, name: 'David Howell' },
  { year: 2025, name: 'Serena Bagnasco' },
  { year: 2026, name: 'Renate Kain' },
  { year: 2027, name: 'Lynn Cornell (incoming)' },
]
